#!/usr/bin/env zsh
set -euo pipefail
IFS=$'\n\t'
set +o nounset  # needed because conda activate uses $BASH_PROFILE

if (( $# == 1 )) && [[ "$1" = "--help" ]]; then
	echo "Makes a new Jupyter notebook from a template and starts a Jupyter server to view it."
	echo "Usage: $0 [notebook-name='untitled.ipynb']"
	exit 0
fi
	

target=untitled.ipynb
if (( $# == 1 )); then
    target=$1
elif (( $# > 1 )); then
    >&2 echo "Usage: $0 [notebook-name='untitled.ipynb']"
    exit 1
fi

if [[ ! "$target" =~ \.ipynb$ ]]; then
	target=$target.ipynb
fi

# TODO remove
if [[ -e "/opt/anaconda3/bin" ]]; then
	export PATH="/opt/anaconda3/bin:$PATH"
fi

if [[ -e $target ]]; then
	>&2 echo "Refusing: ${target} already exists."
else
	cp $KLSCRIPTS/notebooks/template.ipynb $target
	echo "Created $target"
	pth=$(realpath --relative-to=$jupyter_base_dir "$target")
	echo "opening "http://localhost:${jupyter_port}/notebooks/${pth}""
	ker_url="http://localhost:${jupyter_port}/notebooks/${pth}"
	if [[ $OSTYPE =~ "darwin" ]]; then
		open $ker_url
	else
		xdg-open $ker_url
	fi
fi


